---
- name: Create new users 
  user:
   name: '{{ item.name }}'
   groups: wheel
  with_items: "{{ user }}"

- name: Make user to change default password
  shell:
    cmd: chage -d0 "{{ item.name }}"
  with_items: "{{ user }}"

- name: make .ssh direcotry
  file:
    path: "/home/{{ item.name }}/.ssh"
    state: directory
  with_items: "{{ user }}"

- name: create empty authorized_keys file
  file:
    path: "/home/{{ item.name }}/.ssh/authorized_keys"
    state: touch
  with_items: "{{ user }}"
